# HomeWork 001

https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/cohorts/2022/01-intro/homework.md

2022-09-08

## Q1: Version of numpy

In [3]:
import numpy as npy
npy.__version__

'1.21.5'

In [4]:
# by analogy ;-)
import pandas as pda
pda.__version__

'1.4.3'

In [5]:
urlCsv = "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"

In [6]:
dfrCar = pda.read_csv(urlCsv)

In [7]:
dfrCar.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [8]:
dfrCar.describe().round(1)

Year  Engine HP  Engine Cylinders  Number of Doors  highway MPG  \
count  11914.0    11845.0           11884.0          11908.0      11914.0   
mean    2010.4      249.4               5.6              3.4         26.6   
std        7.6      109.2               1.8              0.9          8.9   
min     1990.0       55.0               0.0              2.0         12.0   
25%     2007.0      170.0               4.0              2.0         22.0   
50%     2015.0      227.0               6.0              4.0         26.0   
75%     2016.0      300.0               6.0              4.0         30.0   
max     2017.0     1001.0              16.0              4.0        354.0   

       city mpg  Popularity       MSRP  
count   11914.0     11914.0    11914.0  
mean       19.7      1554.9    40594.7  
std         9.0      1441.9    60109.1  
min         7.0         2.0     2000.0  
25%        16.0       549.0    21000.0  
50%        18.0      1385.0    29995.0  
75%        22.0      2009.0    42231.2  
max       137.0      5657.0  2065902.0

## Q2: number of rows

In [9]:
dfrCar.count()

Make                 11914
Model                11914
Year                 11914
Engine Fuel Type     11911
Engine HP            11845
Engine Cylinders     11884
Transmission Type    11914
Driven_Wheels        11914
Number of Doors      11908
Market Category       8172
Vehicle Size         11914
Vehicle Style        11914
highway MPG          11914
city mpg             11914
Popularity           11914
MSRP                 11914
dtype: int64

In [10]:
dfrCar.index

RangeIndex(start=0, stop=11914, step=1)

In [11]:
dfrCar.count(axis=1)

0        16
1        16
2        16
3        16
4        16
         ..
11909    16
11910    16
11911    16
11912    16
11913    16
Length: 11914, dtype: int64

In [12]:
dfrCar.shape

(11914, 16)

## Q3: Top Make

In [13]:
# verification
dfrCar[ 
        dfrCar['Make']=='Chevrolet'
      ]['Make'].count()

1123

In [14]:
dfrCar['Make'].value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

## Q4: Audi models

In [15]:
dfrCar[  dfrCar['Make']=='Audi'  ]  ['Model'].nunique()

34

In [16]:
# verification
dfrCar[  dfrCar['Make']=='Audi'  ]  ['Model'].unique()

array(['100', '200', '80', '90', 'A3', 'A4 allroad', 'A4', 'A5', 'A6',
       'A7', 'A8', 'allroad quattro', 'allroad', 'Cabriolet', 'Coupe',
       'Q3', 'Q5', 'Q7', 'R8', 'RS 4', 'RS 5', 'RS 6', 'RS 7', 'S3', 'S4',
       'S5', 'S6', 'S7', 'S8', 'SQ5', 'TT RS', 'TT', 'TTS', 'V8'],
      dtype=object)

In [17]:
# verification
dfrCar[  dfrCar['Make']=='Audi'  ]  ['Model'].unique().shape

(34,)

## Q5: Cols with Nulls

In [53]:
dfrCar.isnull().sum() [ dfrCar.isnull().sum() >= 1 ].sort_values(ascending=False)

Market Category     3742
Engine HP             69
Engine Cylinders      30
Number of Doors        6
Engine Fuel Type       3
dtype: int64

In [56]:
len(dfrCar.isnull().sum() [ dfrCar.isnull().sum() >= 1 ])

5

## Q6: "Engine Cylinders"

In [19]:
dfrCar['Engine Cylinders'].median()

6.0

In [20]:
# !! missing 30 records with nan
dfrCar['Engine Cylinders'].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [21]:
# most frequent value for 'Engine Cylinder' in float
floCyl = dfrCar['Engine Cylinders'].value_counts().index[0]
floCyl

4.0

In [22]:
# alternative to get most frequent value
floCyl = dfrCar['Engine Cylinders'].mode().values[0]
floCyl

4.0

In [23]:
# verification: 4752 + 30 nan = 4782 "4.0"
dfrCar['Engine Cylinders'].fillna(floCyl).value_counts()

4.0     4782
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [24]:
dfrCar['Engine Cylinders'].fillna(floCyl).median()

6.0

## Q7: Lotus

In [25]:
arrX = dfrCar[  dfrCar['Make']=='Lotus'  ] [[ 'Engine HP', 'Engine Cylinders']].drop_duplicates().values
arrX

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [26]:
arrX.shape

(9, 2)

In [27]:
# Transpose X in XT
arrXT = arrX.T
arrXT

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [28]:
arrXT.shape

(2, 9)

In [30]:
# Multiply XT by X
arrXTX = arrXT.dot(arrX)
arrXTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [31]:
arrXTX.shape

(2, 2)

In [32]:
# Invert XTX
XTXInv =npy.linalg.inv(arrXTX)
XTXInv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [33]:
# Create y array from list values
arry = npy.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
arry

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [34]:
XTXInv.dot(arrXT)

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [35]:
arrw = XTXInv.dot(arrXT).dot(arry)
arrw

array([  4.59494481, -63.56432501])

In [36]:
# First value =
arrw[0]

4.594944810094579